"""Pure deterministic rendering for packaged Codex member references."""

import json
import re
from typing import Any


_SOURCE_CONTRACT_LINK = re.compile(r"(\[[^]\n]+\]\()contract\.json(\))")


def render_reference(source_id: str, contract: dict[str, Any], instructions: str) -> bytes:
    """Render one exact reference from its frozen source identity and content."""
    normalized = instructions.replace("\r\n", "\n").replace("\r", "\n")
    packaged_contract = f"../contracts/capabilities/{source_id}.json"
    rewritten, link_count = _SOURCE_CONTRACT_LINK.subn(rf"\g<1>{packaged_contract}\g<2>", normalized)
    if link_count == 0:
        raise ValueError(f"source contract link missing: {source_id}")
    title = rewritten.splitlines()[0].removeprefix("# ")
    details = {
        "source_capability_id": source_id,
        "class": contract["class"],
        "profile_of": contract["profile_of"],
        "transition_intent": contract["transition_intent"],
        "final_authority": contract["authority"]["final_authority"],
        "objects": contract["objects"],
        "health_clock": contract["health_clock"],
        "registry_capability_id": contract["registry_capability_id"],
        "canonical_write": contract["mutates_canon"],
        "persistence": contract["runtime_requirements"]["persistence"],
        "logs": contract["runtime_requirements"]["logs"],
        "claims": contract["claims"],
    }
    body = (
        "<!-- Generated from platform-neutral source. Do not edit this file. -->\n"
        f"# {title}\n\n"
        f"Source capability: `{source_id}`\n\n"
        f"Packaged contract: `{packaged_contract}`\n\n"
        f"Qualification receipt: `../contracts/qualification-receipts/{source_id}.json`\n\n"
        "## Machine boundary\n\n"
        "```json\n"
        + json.dumps(details, ensure_ascii=False, indent=2)
        + "\n```\n\n"
        "## Platform-neutral operation\n\n"
        + rewritten.strip()
        + "\n"
    )
    return body.encode("utf-8")
