#!/usr/bin/env python3
"""Deterministically generate or check the local Codex health Skill candidate."""

import argparse
import hashlib
import json
import os
import stat
import sys
from pathlib import Path
from typing import Any


PACKAGE_RELATIVE = Path("dist/codex/yuanli-health")
METADATA_RELATIVE = Path("releases/v0.1.0/release-metadata.json")


def _json_bytes(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_validators(root: Path):
    sys.path.insert(0, str(root / "src"))
    from yuanli_health_skills.validator import (  # pylint: disable=import-outside-toplevel
        validate_contract,
        validate_source_registry,
    )

    return validate_contract, validate_source_registry


def _reference(source_id: str, contract: dict[str, Any], instructions: str) -> bytes:
    title = instructions.splitlines()[0].removeprefix("# ")
    details = {
        "source_capability_id": source_id,
        "class": contract["class"],
        "profile_of": contract["profile_of"],
        "transition_intent": contract["transition_intent"],
        "final_authority": contract["authority"]["final_authority"],
        "objects": contract["objects"],
        "health_clock": contract["health_clock"],
        "registry_capability_id": contract["registry_capability_id"],
        "canonical_write": contract["mutates_canon"],
        "persistence": contract["runtime_requirements"]["persistence"],
        "logs": contract["runtime_requirements"]["logs"],
        "claims": contract["claims"],
    }
    body = (
        "<!-- Generated from platform-neutral source. Do not edit this file. -->\n"
        f"# {title}\n\n"
        f"Source capability: `{source_id}`\n\n"
        f"Packaged contract: `../contracts/capabilities/{source_id}.json`\n\n"
        f"Qualification receipt: `../contracts/qualification-receipts/{source_id}.json`\n\n"
        "## Machine boundary\n\n"
        "```json\n"
        + json.dumps(details, ensure_ascii=False, indent=2)
        + "\n```\n\n"
        "## Platform-neutral operation\n\n"
        + instructions.strip()
        + "\n"
    )
    return body.encode("utf-8")


def _root_skill(source_ids: tuple[str, ...]) -> bytes:
    experience_routes = (
        ("first health session / 首次健康会话", "yuanli.health.experience.first-health-session"),
        ("90-day health experiment / 90 天健康实验", "yuanli.health.experience.ninety-day-health-experiment"),
        ("weekly health checkpoint / 每周健康检查点", "yuanli.health.experience.weekly-health-checkpoint"),
        ("doctor visit preparation / 问诊准备", "yuanli.health.experience.doctor-visit-prep"),
        ("outcome review / 结果复盘", "yuanli.health.experience.outcome-review"),
        ("learning reuse / 学习复用", "yuanli.health.experience.learning-reuse"),
    )
    route_lines = "\n".join(
        f"- {trigger}: read [the exact member reference](references/{source_id}.md)."
        for trigger, source_id in experience_routes
    )
    internal_lines = "\n".join(
        f"- `{source_id}`: [member reference](references/{source_id}.md)"
        for source_id in source_ids
        if source_id not in {item[1] for item in experience_routes}
    )
    return f"""---
name: yuanli-health
description: Use when handling synthetic Yuanli Health candidate work, including First Health Session, health experiments or checkpoints, doctor-visit preparation, outcome review, learning reuse, and explicit internal Kernel or Meta requests.
---

# Yuanli Health

Use this adapter to select one bounded source capability and preserve its machine contract. Inputs stay synthetic and in memory. Never copy real or re-identifiable health material into repository files, receipts, logs, or generated references.

## Decide before routing

Clinical diagnosis, prescription, medication change, chest-pain or urgent/emergency risk never become model conclusions. Stop with concise bilingual guidance to contact a clinician or local emergency services; do not create WPK/ACT or protect a deadline. Refuse persistence and logging even when an owner requests them.

Route only these user JTBDs to Experiences:

{route_lines}

If none matches, return no route. Never fall back to Kernel or Meta and never decide health priority. Kernel and Meta are direct/internal only; read their reference only when the request explicitly names that capability and supplies its prerequisites:

{internal_lines}

## Execute the selected contract

Read only the selected reference and its packaged JSON contract. Preserve supplied facts with evidence references, explicit unknowns and assumptions, final Authority, candidate state, escalation/guardrail, `canonical_write=false`, and `persistence=none`. Do not invent IDs, evidence, receipts, unknown labels, machine fields, or missing prerequisites.

- First Health Session ends at `decision_candidate_ready`; it emits no WPK or ACT.
- OUT requires ACT plus observation; LRN requires OUT; REUSE requires LRN and distinct Task-2 preload/use receipts.
- DEC selects zero or one primary bottleneck and at most two blockers.
- Doctor Visit Prep prepares only supplied questions. Delegate provider selection, booking, pricing, and payment to `yuanli-medical-appointment-operator`; perform none here.
- Meta never self-admits, assigns Registry IDs, claims Human acceptance, tags, releases, publishes, or deploys.

If strict input cannot satisfy the selected member contract, stop at that contract's stable error boundary instead of fabricating an aggregate result. Qualification is synthetic-only: never claim a health outcome, clinical effectiveness, runtime observation, Canon mutation, Registry admission, or publication.
""".encode("utf-8")


def build_package(root: Path) -> tuple[dict[str, bytes], dict[str, Any]]:
    validate_contract, validate_source_registry = _load_validators(root)
    registry = _load_json(root / "registry/source-capabilities.json")
    registry_result = validate_source_registry(registry)
    if not registry_result.ok:
        raise ValueError("source registry is invalid: " + ", ".join(f"{e.code}:{e.path}" for e in registry_result.errors))
    source_ids = tuple(member["source_capability_id"] for member in registry["members"])
    files: dict[str, bytes] = {
        "SKILL.md": _root_skill(source_ids),
        "LICENSE": (root / "LICENSE").read_bytes(),
        "NOTICE": (root / "NOTICE").read_bytes(),
        "contracts/suite-source-manifest.json": _json_bytes(registry),
        "registry-map.json": _json_bytes(
            {
                "schema": "codex-health-registry-map-v1",
                "source_suite_id": registry["source_suite_id"],
                "members": registry["members"],
            }
        ),
    }
    for source_id in source_ids:
        source_directory = root / "capabilities" / source_id
        contract = _load_json(source_directory / "contract.json")
        result = validate_contract(contract)
        if not result.ok:
            raise ValueError(f"invalid source contract {source_id}: " + ", ".join(f"{e.code}:{e.path}" for e in result.errors))
        if contract["source_capability_id"] != source_id:
            raise ValueError(f"source identity mismatch: {source_id}")
        instructions = (source_directory / "instructions.md").read_text(encoding="utf-8").replace("\r\n", "\n")
        files[f"references/{source_id}.md"] = _reference(source_id, contract, instructions)
        files[f"contracts/capabilities/{source_id}.json"] = _json_bytes(contract)
        files[f"contracts/qualification-receipts/{source_id}.json"] = _json_bytes(
            {
                "schema": "qualification-receipt-v1",
                "source_capability_id": source_id,
                "qualification_basis": "synthetic_only",
                "claims": ["non_clinical", "non_release"],
                "candidate_state": "qualified",
                "canonical_write": False,
            }
        )
    checksum_lines = [
        f"{hashlib.sha256(content).hexdigest()}  {relative}\n"
        for relative, content in sorted(files.items())
    ]
    files["SHA256SUMS"] = "".join(checksum_lines).encode("utf-8")
    return files, registry


def _metadata(files: dict[str, bytes], registry: dict[str, Any]) -> dict[str, Any]:
    return {
        "schema": "yuanli-health-release-candidate-v1",
        "version": "0.1.0",
        "source_suite_id": registry["source_suite_id"],
        "catalog_suite_id": registry["catalog_suite_id"],
        "state": "qualified_source_candidate",
        "published": False,
        "registry_admission": False,
        "deployment": "none",
        "release_basis": "synthetic_qualification_only",
        "human_runtime_observed": False,
        "health_outcome": "not_observed",
        "clinical_effectiveness": "not_claimed",
        "n5_pilot": "waived_by_human_owner",
        "package_path": PACKAGE_RELATIVE.as_posix(),
        "package_content_sha256": hashlib.sha256(files["SHA256SUMS"]).hexdigest(),
        "package_file_count": len(files),
        "package_file_count_convention": "all_regular_files_including_SHA256SUMS",
        "source_commit": None,
        "source_tree": None,
        "registry_commit": None,
        "registry_capability_ids": None,
        "resolution_gate": "candidate_commit_then_human_and_registry_gates",
    }


def _existing_files(root: Path) -> tuple[dict[str, bytes], list[str]]:
    if not root.exists():
        return {}, []
    if root.is_symlink() or not root.is_dir():
        return {}, ["package root must be a real directory"]
    files: dict[str, bytes] = {}
    issues: list[str] = []
    for directory, names, filenames in os.walk(root, followlinks=False):
        base = Path(directory)
        for name in names + filenames:
            path = base / name
            mode = path.lstat().st_mode
            relative = path.relative_to(root).as_posix()
            if stat.S_ISLNK(mode):
                issues.append(f"link forbidden: {relative}")
            elif stat.S_ISREG(mode):
                if path.stat().st_nlink != 1:
                    issues.append(f"hardlink forbidden: {relative}")
                else:
                    files[relative] = path.read_bytes()
            elif not stat.S_ISDIR(mode):
                issues.append(f"special file forbidden: {relative}")
    return files, issues


def _clear_output(output: Path) -> None:
    _, issues = _existing_files(output)
    if issues:
        raise ValueError("unsafe generated output: " + "; ".join(issues))
    if not output.exists():
        return
    for path in sorted(output.rglob("*"), key=lambda item: len(item.parts), reverse=True):
        if path.is_file():
            path.unlink()
        else:
            path.rmdir()


def _write_package(output: Path, files: dict[str, bytes]) -> None:
    _clear_output(output)
    output.mkdir(parents=True, exist_ok=True)
    for relative, content in sorted(files.items()):
        path = output / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--output", type=Path)
    parser.add_argument("--metadata", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    output = args.output.resolve() if args.output else root / PACKAGE_RELATIVE
    metadata_path = args.metadata.resolve() if args.metadata else (root / METADATA_RELATIVE if args.output is None else None)
    try:
        files, registry = build_package(root)
        metadata = _metadata(files, registry)
        if args.check:
            existing, issues = _existing_files(output)
            if issues or existing != files:
                print("generated package is missing, extra, unsafe, or byte-different", file=sys.stderr)
                return 1
            if metadata_path is not None and (not metadata_path.is_file() or metadata_path.read_bytes() != _json_bytes(metadata)):
                print("release metadata is missing or byte-different", file=sys.stderr)
                return 1
        else:
            _write_package(output, files)
            if metadata_path is not None:
                metadata_path.parent.mkdir(parents=True, exist_ok=True)
                metadata_path.write_bytes(_json_bytes(metadata))
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"generation failed: {exc}", file=sys.stderr)
        return 1
    print(f"adapter OK files={len(files)} content_sha256={hashlib.sha256(files['SHA256SUMS']).hexdigest()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
