#!/usr/bin/env python3
"""Validate a generated Codex health Skill candidate using the standard library."""

import argparse
import contextlib
import hashlib
import json
import sys
import tomllib
from pathlib import Path
from typing import Any

from codex_adapter_reference import (
    read_instruction_source,
    render_checksum_manifest,
    render_reference,
    render_root,
    validate_instruction_operation,
)
from lexical_path_guard import (
    LexicalPathIdentity,
    absolute_lexical_path,
    inspect_lexical_path,
    revalidate_lexical_path,
)


PACKAGE_RELATIVE = Path("dist/codex/yuanli-health")
METADATA_RELATIVE = Path("releases/v0.1.0/release-metadata.json")


class DuplicateKeyError(ValueError):
    pass


def _object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise DuplicateKeyError(key)
        result[key] = value
    return result


def _json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=_object)


def _json_bytes(content: bytes) -> Any:
    return json.loads(content.decode("utf-8"), object_pairs_hook=_object)


def _load_validators(root: Path):
    sys.path.insert(0, str(root / "src"))
    from yuanli_health_skills.validator import (  # pylint: disable=import-outside-toplevel
        validate_contract,
        validate_receipt,
        validate_source_registry,
    )

    return validate_contract, validate_receipt, validate_source_registry


def _inspect(package: LexicalPathIdentity) -> tuple[dict[str, bytes], list[str]]:
    return package.snapshot(reject_executable=True, missing_issue=True)


def _frontmatter(content: str) -> dict[str, str] | None:
    if not content.startswith("---\n"):
        return None
    end = content.find("\n---\n", 4)
    if end < 0:
        return None
    result: dict[str, str] = {}
    for line in content[4:end].splitlines():
        if ":" not in line:
            return None
        key, value = line.split(":", 1)
        if key in result:
            return None
        result[key.strip()] = value.strip()
    return result


def _expected_paths(source_ids: tuple[str, ...]) -> set[str]:
    paths = {"SKILL.md", "LICENSE", "NOTICE", "registry-map.json", "SHA256SUMS", "contracts/suite-source-manifest.json"}
    paths.update(f"references/{item}.md" for item in source_ids)
    paths.update(f"contracts/capabilities/{item}.json" for item in source_ids)
    paths.update(f"contracts/qualification-receipts/{item}.json" for item in source_ids)
    return paths


def _reference_details(source_id: str, contract: dict[str, Any]) -> dict[str, Any]:
    return {
        "source_capability_id": source_id,
        "class": contract["class"],
        "profile_of": contract["profile_of"],
        "transition_intent": contract["transition_intent"],
        "final_authority": contract["authority"]["final_authority"],
        "objects": contract["objects"],
        "health_clock": contract["health_clock"],
        "registry_capability_id": contract["registry_capability_id"],
        "canonical_write": contract["mutates_canon"],
        "persistence": contract["runtime_requirements"]["persistence"],
        "logs": contract["runtime_requirements"]["logs"],
        "claims": contract["claims"],
    }


def _reference_prefix(source_id: str, contract: dict[str, Any], title: str) -> bytes:
    packaged_contract = f"../contracts/capabilities/{source_id}.json"
    return (
        "<!-- Generated from platform-neutral source. Do not edit this file. -->\n"
        f"# {title}\n\n"
        f"Source capability: `{source_id}`\n\n"
        f"Packaged contract: `{packaged_contract}`\n\n"
        f"Qualification receipt: `../contracts/qualification-receipts/{source_id}.json`\n\n"
        "## Machine boundary\n\n"
        "```json\n"
        + json.dumps(_reference_details(source_id, contract), ensure_ascii=False, indent=2)
        + "\n```\n\n"
        "## Platform-neutral operation\n\n"
    ).encode("utf-8")


def _validate_emitted_markdown(
    files: dict[str, bytes],
    source_ids: tuple[str, ...],
    contracts: dict[str, dict[str, Any]],
) -> list[str]:
    """Validate only the fixed generated root/reference grammar, never arbitrary Markdown."""
    issues: list[str] = []
    if files["SKILL.md"] != render_root(source_ids):
        issues.append("generated Markdown byte mismatch: SKILL.md")
    for source_id in source_ids:
        relative = f"references/{source_id}.md"
        try:
            content = files[relative].decode("utf-8")
            marker = "## Platform-neutral operation\n\n"
            prefix_without_marker, found, projection = content.partition(marker)
            if not found or marker in projection:
                raise ValueError("fixed projection boundary mismatch")
            prefix_lines = prefix_without_marker.splitlines()
            if len(prefix_lines) < 2 or not prefix_lines[1].startswith("# "):
                raise ValueError("generated title mismatch")
            title = prefix_lines[1][2:]
            expected_prefix = _reference_prefix(source_id, contracts[source_id], title).decode("utf-8")
            if prefix_without_marker + marker != expected_prefix:
                raise ValueError("fixed reference prefix mismatch")
            validate_instruction_operation(
                source_id,
                title,
                projection,
                f"../contracts/capabilities/{source_id}.json",
            )
        except (KeyError, UnicodeDecodeError, ValueError):
            issues.append(f"generated Markdown structure mismatch: {relative}")
    return issues


def validate_package(
    root: Path,
    package: LexicalPathIdentity,
) -> tuple[list[str], str | None, int]:
    validate_contract, validate_receipt, validate_source_registry = _load_validators(root)
    issues: list[str] = []
    files, inspection = _inspect(package)
    issues.extend(inspection)
    required_scaffolds = {
        "SKILL.md",
        "LICENSE",
        "NOTICE",
        "registry-map.json",
        "SHA256SUMS",
        "contracts/suite-source-manifest.json",
    }
    missing_scaffolds = required_scaffolds - set(files)
    if missing_scaffolds:
        issues.append(f"package scaffolds missing: {sorted(missing_scaffolds)}")
    if issues:
        return issues, None, len(files)

    manifest = _json_bytes(files["contracts/suite-source-manifest.json"])
    manifest_result = validate_source_registry(manifest)
    if not manifest_result.ok:
        issues.append("suite source manifest invalid")
        return issues, None, len(files)
    source_ids = tuple(member["source_capability_id"] for member in manifest["members"])
    expected = _expected_paths(source_ids)
    if set(files) != expected:
        issues.append(f"package paths differ: missing={sorted(expected - set(files))} extra={sorted(set(files) - expected)}")
    if issues:
        return issues, None, len(files)

    contracts = {
        source_id: _json_bytes(files[f"contracts/capabilities/{source_id}.json"])
        for source_id in source_ids
    }
    issues.extend(_validate_emitted_markdown(files, source_ids, contracts))

    source_registry = _json(root / "registry/source-capabilities.json")
    if manifest != source_registry:
        issues.append("suite source manifest mismatch")
    expected_markdown: dict[str, bytes] = {"SKILL.md": render_root(source_ids)}
    for source_id in source_ids:
        source_directory = root / "capabilities" / source_id
        source_contract = _json(source_directory / "contract.json")
        try:
            source_instructions = read_instruction_source(
                source_directory / "instructions.md",
                source_id,
            )
            expected_markdown[f"references/{source_id}.md"] = render_reference(
                source_id,
                source_contract,
                source_instructions,
            )
        except ValueError as exc:
            issues.append(f"repository source Markdown rejected: {source_id}: {exc}")
    for markdown_path, expected_bytes in expected_markdown.items():
        if files[markdown_path] != expected_bytes:
            issues.append(f"generated Markdown byte mismatch: {markdown_path}")

    canonical_checksums = render_checksum_manifest(files)
    if files["SHA256SUMS"] != canonical_checksums:
        issues.append("non-canonical SHA256SUMS")

    frontmatter = _frontmatter(files["SKILL.md"].decode("utf-8"))
    if frontmatter is None or set(frontmatter) != {"name", "description"}:
        issues.append("malformed Skill frontmatter")
    elif frontmatter["name"] != "yuanli-health" or not frontmatter["description"].startswith("Use when"):
        issues.append("invalid Skill discovery metadata")

    registry_map = _json_bytes(files["registry-map.json"])
    expected_map = {
        "schema": "codex-health-registry-map-v1",
        "source_suite_id": manifest["source_suite_id"],
        "members": manifest["members"],
    }
    if registry_map != expected_map:
        issues.append("registry map identity/order/null mismatch")

    for source_id in source_ids:
        contract = contracts[source_id]
        receipt = _json_bytes(files[f"contracts/qualification-receipts/{source_id}.json"])
        if not validate_contract(contract).ok:
            issues.append(f"contract mismatch: {source_id}")
        source_contract = _json(root / "capabilities" / source_id / "contract.json")
        if contract != source_contract:
            issues.append(f"contract mismatch: {source_id}")
        expected_receipt = {
            "schema": "qualification-receipt-v1",
            "source_capability_id": source_id,
            "qualification_basis": "synthetic_only",
            "claims": ["non_clinical", "non_release"],
            "candidate_state": "qualified",
            "canonical_write": False,
        }
        if not validate_receipt(receipt).ok or receipt != expected_receipt:
            issues.append(f"receipt mismatch: {source_id}")
        reference_bytes = files[f"references/{source_id}.md"]
        reference = reference_bytes.decode("utf-8")
        if reference.count(f"Source capability: `{source_id}`") != 1:
            issues.append(f"reference identity mismatch: {source_id}")

    if files["LICENSE"] != (root / "LICENSE").read_bytes() or not files["LICENSE"].startswith(b"Apache License\nVersion 2.0"):
        issues.append("license mismatch")
    if files["NOTICE"] != (root / "NOTICE").read_bytes():
        issues.append("notice mismatch")
    if not issues:
        final_files, final_inspection = _inspect(package)
        if final_inspection or final_files != files:
            issues.append("package changed after validation")
    return issues, hashlib.sha256(files["SHA256SUMS"]).hexdigest(), len(files)


def validate_metadata(content: bytes, content_hash: str, file_count: int) -> list[str]:
    document = _json_bytes(content)
    expected = {
        "schema": "yuanli-health-release-candidate-v1",
        "version": "0.1.0",
        "source_suite_id": "YL-SUITE-HEALTH-20260823-0001",
        "catalog_suite_id": "zk:suite:yuanli-health",
        "state": "qualified_source_candidate",
        "published": False,
        "registry_admission": False,
        "deployment": "none",
        "release_basis": "synthetic_qualification_only",
        "human_runtime_observed": False,
        "health_outcome": "not_observed",
        "clinical_effectiveness": "not_claimed",
        "n5_pilot": "waived_by_human_owner",
        "package_path": "dist/codex/yuanli-health",
        "package_content_sha256": content_hash,
        "package_file_count": file_count,
        "package_file_count_convention": "all_regular_files_including_SHA256SUMS",
        "source_commit": None,
        "source_tree": None,
        "registry_commit": None,
        "registry_capability_ids": None,
        "resolution_gate": "candidate_commit_then_human_and_registry_gates",
    }
    return [] if document == expected else ["release metadata mismatch or false release claim"]


def validate_repository(root: Path) -> list[str]:
    issues: list[str] = []
    license_text = (root / "LICENSE").read_text(encoding="utf-8")
    if not license_text.startswith("Apache License\nVersion 2.0") or "END OF TERMS AND CONDITIONS" not in license_text:
        issues.append("root license is not Apache-2.0")
    readme = (root / "README.md").read_text(encoding="utf-8").lower()
    for required in ("16 qualified", "synthetic-only", "qualified source candidate", "not released", "registry-admitted", "canon"):
        if required not in readme:
            issues.append(f"README candidate boundary missing: {required}")
    workflow = (root / ".github/workflows/health-skills-ci.yml").read_text(encoding="utf-8")
    forbidden = ("secrets.", "pull_request_target", "permissions: write", "contents: write")
    if any(item in workflow for item in forbidden):
        issues.append("workflow secret or write authority forbidden")
    for required in (
        "python3 -m unittest discover -s tests -v",
        "scripts/validate_capabilities.py",
        "scripts/generate_codex_adapter.py --check",
        "scripts/validate_codex_adapter.py --check-repository",
        "scripts/scan_public_content.py --check-current --check-history",
        "fetch-depth: 0",
    ):
        if required not in workflow:
            issues.append(f"workflow gate missing: {required}")
    project = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))["project"]
    if project.get("requires-python") != ">=3.11" or project.get("dependencies") != []:
        issues.append("runtime dependency boundary changed")
    return issues


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--package", type=Path)
    parser.add_argument("--metadata", type=Path)
    parser.add_argument("--check-repository", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    package = absolute_lexical_path(args.package) if args.package else root / PACKAGE_RELATIVE
    metadata = absolute_lexical_path(args.metadata) if args.metadata else (root / METADATA_RELATIVE if args.check_repository else None)
    try:
        with contextlib.ExitStack() as stack:
            package_identity = stack.enter_context(inspect_lexical_path(package))
            metadata_identity = stack.enter_context(inspect_lexical_path(metadata.parent)) if metadata is not None else None
            revalidate_lexical_path(package_identity)
            issues, content_hash, file_count = validate_package(root, package_identity)
            if not issues and metadata_identity is not None:
                issues.extend(
                    validate_metadata(
                        metadata_identity.read_regular_file(metadata.name),
                        content_hash or "",
                        file_count,
                    )
                )
            if args.check_repository:
                issues.extend(validate_repository(root))
    except (OSError, ValueError, json.JSONDecodeError, DuplicateKeyError, ImportError) as exc:
        issues = [f"validation exception: {exc}"]
        content_hash = None
        file_count = 0
    for issue in issues:
        print(issue, file=sys.stderr)
    if issues:
        return 1
    print(f"adapter valid files={file_count} content_sha256={content_hash}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
